name: Test
on: [ push, pull_request ]
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer
      - name: Install
        run: composer install --no-interaction
      - name: Unit tests
        run: |
          composer test
          sed -i 's#'$GITHUB_WORKSPACE'#/github/workspace#g' tests-*.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        if: matrix.php == '8.2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install
        run: |
          composer install --no-interaction
          npm ci
      - name: Code style checks for PHP, JS and CSS
        run: composer lint-all
