name: Test
on: push
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer
      - name: Install
        run: composer install --no-interaction
      - name: Unit tests
        run: composer test
      - name: Coverage Report
        if: matrix.php == '8.1'
        uses: codecov/codecov-action@v3
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install
        run: |
          composer install --no-interaction
          npm ci
      - name: Code style checks for PHP, JS and CSS
        run: composer lint-all
